# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YouWatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouWatch

  target 'YouWatchTests' do
pod 'PullToRefresher', '~> 3.0'
  
  end

end
